AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple API Endpoint configured using Swagger specified inline and backed by a Lambda function
Resources:
  SAMLamGET:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get.handler
      Runtime: nodejs8.10
      CodeUri: ./src/get.js
      Events:
        ApiGETEvent:
          Type: Api
          Properties:
            RestApiId: !Ref SAMApi
            Path: /route
            Method: GET
  SAMLamPOST:
    Type: AWS::Serverless::Function
    Properties:
      Handler: post.handler
      Runtime: nodejs8.10
      CodeUri: ./src/post.js
      Events:
        ApiPOSTEvent:
          Type: Api
          Properties:
            RestApiId: !Ref SAMApi
            Path: /route
            Method: POST
  SAMApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: stage
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: s3://<your-bucket-name>/swagger.json