AWSTemplateFormatVersion: '2010-09-09'
Description: Simple API Endpoint configured using Swagger specified inline and backed
  by a Lambda function
Resources:
  SAMApi:
    Properties:
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://super-secret-dont-read-me/swagger.json
      StageName: stage
    Type: AWS::Serverless::Api
  SAMLamGET:
    Properties:
      CodeUri: s3://sam-stamp/6aa95c449a69f714766624fa81b7015c
      Events:
        ApiGETEvent:
          Properties:
            Method: GET
            Path: /route
            RestApiId:
              Ref: SAMApi
          Type: Api
      Handler: get.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  SAMLamPOST:
    Properties:
      CodeUri: s3://sam-stamp/764093f3b54e35ba821aefa851ae38c3
      Events:
        ApiPOSTEvent:
          Properties:
            Method: POST
            Path: /route
            RestApiId:
              Ref: SAMApi
          Type: Api
      Handler: post.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
